CREATE TABLE cars(
                     id smallserial primary key generated by default as identity,
                     brand TEXT,
                     model TEXT,
                     price INTEGER check ( price>0 )
);

CREATE TABLE driver (
                        id SMALLSERIAL primary key generated by default as identity,
                        name text,
                        age SMALLINT CHECK ( age>=18 ),
                        drivingLicence BOOLEAN,
                        car smallint REFERENCES cars(id)
);